#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : gnome-common
Version  : 3.18.0
Release  : 1
URL      : https://download.gnome.org/sources/gnome-common/3.18/gnome-common-3.18.0.tar.xz
Source0  : https://download.gnome.org/sources/gnome-common/3.18/gnome-common-3.18.0.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: gnome-common-bin

%description
This module contains various files needed to bootstrap GNOME modules
built from git.  It contains the following components:
1. A common "autogen.sh" script that can be used to configure a
source directory checked out from git.
2. Some commonly used macros (quite a small set these days -- macros
should be packaged with their respective modules).

%package bin
Summary: bin components for the gnome-common package.
Group: Binaries

%description bin
bin components for the gnome-common package.


%package dev
Summary: dev components for the gnome-common package.
Group: Development
Requires: gnome-common-bin
Provides: gnome-common-devel

%description dev
dev components for the gnome-common package.


%prep
%setup -q -n gnome-common-3.18.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1513199385
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1513199385
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/gnome-autogen.sh

%files dev
%defattr(-,root,root,-)
/usr/share/aclocal/*.m4
